---
- name: Destroy Terraform Infrastructure on AWS
  hosts: all
  connection: local
  vars_prompt:

  - name: aws_region
    prompt: AWS region 
    default: "eu-central-1"
    private: false
    
  - name: backend_bucket
    prompt: S3_bucket_name (tfstate-vmon-[timestamp]) 
    private: false

  tasks:
  
    #- name: Debug
    - debug:
        msg: "backend_bucket_name: {{ backend_bucket }}, aws_region: {{ aws_region }}"
  
    - name: Destroy the configuration
      command: terraform destroy -var="region={{ aws_region }}" --auto-approve 
      register: tf_infrastructure_destroyed

    - name: Destroy DDB table
      community.aws.dynamodb_table:
        name: tfstate-lock-vmon
        state: absent
        hash_key_name: LockID
        region: "{{ aws_region }}"
      register: destroyed_ddb_table

    - name: Destroy S3 bucket 
      amazon.aws.s3_bucket:
        name: "{{ backend_bucket }}"
        state: absent
        versioning: on
        region: "{{ aws_region }}"
      register: destroyed_bucket 


