---
- name: Create Terraform Infrastructure on AWS

  hosts: all
  connection: local

  vars_prompt:
    
  - name: aws_region
    prompt: AWS region to deploy
    #default: "eu-central-1"
    private: false

  - name: backend_bucket
    prompt: S3_bucket_name (tfstate-vmon-[timestamp]) 
    private: false
  
  tasks:

    - debug:
        msg: "backend_bucket_name: {{ backend_bucket }}, aws_region: {{ aws_region }}"

    - name: Initialize Terraform
      command: chdir=modules/grafana terraform init -backend-config="bucket={{ backend_bucket }}" -backend-config="region={{ aws_region }}"
      register: initialized_terraform
  
    - name: Create execution plan
      command: chdir=modules/grafana terraform plan -var="backend_bucket={{ backend_bucket }}" -var="region={{ aws_region }}" -out="tfplan" 
      register: created_tfplan
  
    - name: Deploy the planned configuration
      command: chdir=modules/grafana terraform apply --auto-approve "tfplan" 
      register: infrastructure_deployed
