global:

  scrape_interval:     15s # Scrape targets every 15 seconds by default. Range vector selectors then aggregate N of these in every [R] & hand off to a function (e.g. rate) to condense the series to a single output that can be graphed. See records.yml.
  evaluation_interval: 15s # Recommended best practice to be kept the same as scrape_interval


rule_files:

  - 'alerts.yml'
  #- 'records.yml'


scrape_configs:

  # The following job is for the embedded_exporter on the Prometheus app itself;
  
  #- job_name: 'host_embedded'

  #  static_configs:

  #    - targets: ['localhost:9090'] # points to container localhost
  #      labels:
  #        country: 'Finland'
  #        region: 'eu-central-f'
  #        stage: 'prod'


  # The following job is for the prom_node_exporter installed on the Prometheus host (which also hosts Grafana & Nginx containers, alongside it);

  - job_name: 'pne_host'

    static_configs:

      - targets: ['host.docker.internal:9100'] # this points the VM's phy-IP and not the container localhost, since node_exporter is running on the actual VM itself while the prometheus app is inside a docker network.
        labels:
          country: 'Finland'
          region: 'eu-central-f' # Mock region for demonstration purposes on Grafana world map. Also see: configs/grafana/geo.json
          stage: 'prod'


  # These are the remote instances (i.e. VMs) with prom_node_exporter (PNE) installed & scraped by the Prometheus Host;

  - job_name: 'pne_clients'

    static_configs:

      - targets: ['fra-0.vmon.zenite.uk:9100']
        labels:
          country: 'Germany'
          region: 'eu-central-1'
          stage: 'prod'

      - targets: ['lon-0.vmon.zenite.uk:9100']
        labels:
          country: 'United Kingdom'
          region: 'eu-west-2'
          stage: 'dev'

      - targets: ['sfc-0.vmon.zenite.uk:9100']
        labels:
          country: 'USA'
          region: 'us-west-1'
          stage: 'dev'

      - targets: ['nyc-0.vmon.zenite.uk:9100']
        labels:
          country: 'USA'
          region: 'us-east-1-nyc'
          stage: 'dev'

      - targets: ['tyo-0.vmon.zenite.uk:9100']
        labels:
          country: 'Japan'
          region: 'ap-northeast-1'
          stage: 'dev'

  # These are the remote instances (i.e. serverless containers) with google_container_advisor (GCA) installed & scraped by the Prometheus Host;

  - job_name: 'gca_clients'

    static_configs:

      - targets: ['dxb-0.vmon.zenite.uk:9100']
        labels:
          country: 'UAE'
          region: 'me-central-1'
          stage: 'dev'

      - targets: ['sgp-0.vmon.zenite.uk:9100']
        labels:
          country: 'Singapore'
          region: 'ap-southeast-1'
          stage: 'dev'