version: "3"
name: nr-vmon

networks:
  nr-vnet:
    name: nr-vnet
    driver: bridge

volumes:
  prom_data:
  graf_data:

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - prom_data:/data/prometheus                                       # named volume on the EBS data-disk to persist TSDB (path relative to Docker root directory)
      - /etc/docker/prometheus:/etc/prometheus                           # bind-mounted config directory
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=/prom/'                                      # to allow path-based routing by the nginx-proxy. This is matched in the nginx.conf location block
    networks:
      - nr-vnet
    extra_hosts:
    - "host.docker.internal:host-gateway"                                # allow Prometheus container connect to the underlying host VM for HTTP scraping
  grafana:
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    links:
      - "prometheus:prometheus"
    volumes:
      - graf_data:/var/lib/grafana                                        # named volume on the EBS data-disk to persist dashboard data (path relative to Docker root directory)
    environment:
      #py#GF_SERVER_DOMAIN: DOMAIN_NAME                                   # managed by putScripts.py
      GF_SERVER_SERVE_FROM_SUB_PATH: true                                 # to allow path-based routing by the nginx-proxy.
      GF_SERVER_ROOT_URL:	'%(protocol)s://%(domain)s:%(http_port)s/graf/' # this is matched in the nginx.conf location block
    networks:
      - nr-vnet
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    #links:
    #  - "prometheus:prometheus"
    #  - "grafana:grafana"
    volumes:
      - /etc/docker/nginx/conf.d:/etc/nginx/conf.d
      - /etc/docker/nginx/ssl:/etc/nginx/ssl
    #  - /etc/docker/www:/var/www
    networks:
      - nr-vnet