version: "3"
name: nr-vmon

networks:
  nr-vnet:
    name: nr-vnet
    driver: bridge

volumes:
  prom_data:
  graf_data:

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prom_data:/data/prometheus # named volume on the EBS data-disk to persist TSDB (path relative to Docker root directory)
      - /etc/docker/prometheus:/etc/prometheus # bind-mounted config directory
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - nr-vnet
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - "prometheus:prometheus"
    volumes:
      - graf_data:/var/lib/grafana # named volume on the EBS data-disk to persist dashboard data (path relative to Docker root directory)
    networks:
      - nr-vnet
