version: "0.1"
name: netradar_vmmon

networks:
  vmmon:
    name: vmmon
    driver: bridge

volumes:
  prom_data:
  graf_data:

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prom_data:/etc/prometheus
      - /opt/docker/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - vmmon
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - graf_data:/var/lib/grafana
    networks:
      - vmmon
